/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GiveMeMoneyJFrame.java
 *
 * Created on 2012-12-27, 21:54:47
 */

package com.jd.jaffee.gmm.view;

import com.jd.jaffee.gmm.domain.BillInfo;
import com.jd.jaffee.gmm.domain.LunchInfo;
import com.jd.jaffee.gmm.domain.User;
import com.jd.jaffee.gmm.service.BillInfoService;
import com.jd.jaffee.gmm.service.LunchInfoService;
import com.jd.jaffee.gmm.service.UserService;
import com.jd.jaffee.gmm.service.impl.BillInfoServiceImpl;
import com.jd.jaffee.gmm.service.impl.LunchInfoServiceImpl;
import com.jd.jaffee.gmm.service.impl.UserServiceImpl;
import com.jd.jaffee.gmm.utils.DateUtil;
import com.jd.jaffee.gmm.utils.RestaurantUtil;
import com.jd.jaffee.gmm.utils.StringUtil;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Jaffee
 */
public class GiveMeMoneyJFrame extends javax.swing.JFrame {

    private UserService userService = new UserServiceImpl();
    private LunchInfoService lunchInfoService = new LunchInfoServiceImpl();
    private BillInfoService billInfoService = new BillInfoServiceImpl();
    private int payBillId = 0;

    /** Creates new form GiveMeMoneyJFrame */
    public GiveMeMoneyJFrame() {
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
            Logger.getLogger(GiveMeMoneyJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        billInfoJTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent event) {
                if (event.isPopupTrigger()) {
                    billInfoTableJPopupMenu.show(event.getComponent(), event.getX(), event.getY());
                }
            }
        });
    }

    private void initAddLunchPanel(){
        String[] restaurantNames = RestaurantUtil.getRestaurantNames();
        if(restaurantNames != null && restaurantNames.length > 0){
            restaurantJComboBox.setModel(new DefaultComboBoxModel(restaurantNames));
        }
        this.lunchDateJTextField.setText(DateUtil.getCurrentShortDateString());
        this.lunchWeekJTextField.setText(DateUtil.getDayOfWeek());
        this.lunchUserJPanel.removeAll();
        List<User> users = userService.queryAllUser();
        if(users != null && users.size() > 0){
            for(User user : users){
                JCheckBox box = new JCheckBox();
                box.setText(user.getUserName());
                box.setActionCommand(user.getId() + "");
                box.setVisible(true);
                this.lunchUserJPanel.add(box);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billInfoTableJPopupMenu = new javax.swing.JPopupMenu();
        payBillJMenuItem = new javax.swing.JMenuItem();
        unpayBillJMenuItem = new javax.swing.JMenuItem();
        mainJDesktopPane = new javax.swing.JDesktopPane();
        addUserInfoJInternalFrame = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userEmailJTextField = new javax.swing.JTextField();
        userPhoneNumberJTextField = new javax.swing.JTextField();
        submitUserInfoJButton = new javax.swing.JButton();
        addLunchInfoJInternalFrame = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        restaurantJComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        lunchDateJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        allMoneyJTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        averageMoneyJTextField = new javax.swing.JTextField();
        lunchWeekJTextField = new javax.swing.JTextField();
        lunchUserJPanel = new javax.swing.JPanel();
        addLunchInfoJButton = new javax.swing.JButton();
        showLunchInfoJInternalFrame = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        queryLunchResJComboBox = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        queryLunchSubmitJButton = new javax.swing.JButton();
        queryLunchBtJTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        queryLunchEtJTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        queryLunchInfoWeekJComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lunchInfoJTable = new javax.swing.JTable();
        billInfoJInternalFrame = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        todayBillInfoJCheckBox = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        billInfoBeginDateJTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        billInfoWeekJComboBox = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        billInfoPayJComboBox = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        billInfoUserNameJTextField = new javax.swing.JTextField();
        billInfoSubmitJButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        billInfoEndDateJTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        billInfoJTable = new javax.swing.JTable();
        payBillJInternalFrame = new javax.swing.JInternalFrame();
        jLabel18 = new javax.swing.JLabel();
        payBillUserNameJTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        payBillMoneyJTextField = new javax.swing.JTextField();
        payBillSubmitJButton = new javax.swing.JButton();
        mainMenuBar = new javax.swing.JMenuBar();
        userInofJMenu = new javax.swing.JMenu();
        addUserInfoJMenuItem = new javax.swing.JMenuItem();
        queryUserInfoJMenuItem = new javax.swing.JMenuItem();
        LunchInfoJMenu = new javax.swing.JMenu();
        addLunchInfoMenuItem = new javax.swing.JMenuItem();
        queryLunchJMenuItem = new javax.swing.JMenuItem();
        billInfoJMenu = new javax.swing.JMenu();
        billInfoJMenuItem = new javax.swing.JMenuItem();

        payBillJMenuItem.setText("填写付款信息");
        payBillJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBillJMenuItemActionPerformed(evt);
            }
        });
        billInfoTableJPopupMenu.add(payBillJMenuItem);

        unpayBillJMenuItem.setText("标记为未付款");
        unpayBillJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unpayBillJMenuItemActionPerformed(evt);
            }
        });
        billInfoTableJPopupMenu.add(unpayBillJMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("给钱否？");

        addUserInfoJInternalFrame.setClosable(true);
        addUserInfoJInternalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addUserInfoJInternalFrame.setTitle("添加饭友信息");
        addUserInfoJInternalFrame.setPreferredSize(new java.awt.Dimension(430, 210));

        jLabel1.setText("姓名：");

        jLabel2.setText("邮箱：");

        jLabel3.setText("手机：");

        submitUserInfoJButton.setText("提交");
        submitUserInfoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitUserInfoJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addUserInfoJInternalFrameLayout = new javax.swing.GroupLayout(addUserInfoJInternalFrame.getContentPane());
        addUserInfoJInternalFrame.getContentPane().setLayout(addUserInfoJInternalFrameLayout);
        addUserInfoJInternalFrameLayout.setHorizontalGroup(
            addUserInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserInfoJInternalFrameLayout.createSequentialGroup()
                .addGroup(addUserInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addUserInfoJInternalFrameLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(addUserInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addUserInfoJInternalFrameLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(userPhoneNumberJTextField))
                            .addGroup(addUserInfoJInternalFrameLayout.createSequentialGroup()
                                .addGroup(addUserInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(addUserInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userEmailJTextField)
                                    .addComponent(userNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))))
                    .addGroup(addUserInfoJInternalFrameLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(submitUserInfoJButton)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        addUserInfoJInternalFrameLayout.setVerticalGroup(
            addUserInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserInfoJInternalFrameLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(addUserInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addUserInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userEmailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addUserInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userPhoneNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(submitUserInfoJButton)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        addUserInfoJInternalFrame.setBounds(30, 30, 430, 230);
        mainJDesktopPane.add(addUserInfoJInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        addLunchInfoJInternalFrame.setClosable(true);
        addLunchInfoJInternalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addLunchInfoJInternalFrame.setTitle("添加午饭信息");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("午饭信息"));

        jLabel4.setText("饭馆：");

        restaurantJComboBox.setEditable(true);

        jLabel5.setText("日期：");

        jLabel6.setText("星期：");

        jLabel7.setText("总金额：");

        jLabel8.setText("人均：");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(restaurantJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lunchDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lunchWeekJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allMoneyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(averageMoneyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(restaurantJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunchDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(lunchWeekJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(allMoneyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(averageMoneyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lunchUserJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("人员信息"));
        lunchUserJPanel.setAutoscrolls(true);
        lunchUserJPanel.setLayout(new java.awt.GridLayout(5, 5));

        addLunchInfoJButton.setText("提交");
        addLunchInfoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLunchInfoJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addLunchInfoJInternalFrameLayout = new javax.swing.GroupLayout(addLunchInfoJInternalFrame.getContentPane());
        addLunchInfoJInternalFrame.getContentPane().setLayout(addLunchInfoJInternalFrameLayout);
        addLunchInfoJInternalFrameLayout.setHorizontalGroup(
            addLunchInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addLunchInfoJInternalFrameLayout.createSequentialGroup()
                .addGroup(addLunchInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addLunchInfoJInternalFrameLayout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(addLunchInfoJButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addLunchInfoJInternalFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addLunchInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lunchUserJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        addLunchInfoJInternalFrameLayout.setVerticalGroup(
            addLunchInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLunchInfoJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lunchUserJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(addLunchInfoJButton)
                .addGap(32, 32, 32))
        );

        addLunchInfoJInternalFrame.setBounds(10, 20, 790, 370);
        mainJDesktopPane.add(addLunchInfoJInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        showLunchInfoJInternalFrame.setClosable(true);
        showLunchInfoJInternalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        showLunchInfoJInternalFrame.setMaximizable(true);
        showLunchInfoJInternalFrame.setResizable(true);
        showLunchInfoJInternalFrame.setTitle("午饭信息查询");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel9.setText("饭馆：");

        jLabel10.setText("开始日期：");

        queryLunchSubmitJButton.setText("查询");
        queryLunchSubmitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryLunchSubmitJButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("结束日期：");

        jLabel12.setText("星期：");

        queryLunchInfoWeekJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期天" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(queryLunchResJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(queryLunchBtJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(queryLunchEtJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(queryLunchInfoWeekJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(queryLunchSubmitJButton)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(queryLunchResJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(queryLunchBtJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(queryLunchEtJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(queryLunchSubmitJButton)
                    .addComponent(queryLunchInfoWeekJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lunchInfoJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "编号", "日期", "星期", "饭馆", "总数", "人均", "名单"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lunchInfoJTable);

        javax.swing.GroupLayout showLunchInfoJInternalFrameLayout = new javax.swing.GroupLayout(showLunchInfoJInternalFrame.getContentPane());
        showLunchInfoJInternalFrame.getContentPane().setLayout(showLunchInfoJInternalFrameLayout);
        showLunchInfoJInternalFrameLayout.setHorizontalGroup(
            showLunchInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
        );
        showLunchInfoJInternalFrameLayout.setVerticalGroup(
            showLunchInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showLunchInfoJInternalFrameLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        showLunchInfoJInternalFrame.setBounds(0, 0, 850, 410);
        mainJDesktopPane.add(showLunchInfoJInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        billInfoJInternalFrame.setClosable(true);
        billInfoJInternalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        billInfoJInternalFrame.setMaximizable(true);
        billInfoJInternalFrame.setResizable(true);
        billInfoJInternalFrame.setTitle("账单信息查看");

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 100));

        todayBillInfoJCheckBox.setText("今日");
        todayBillInfoJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayBillInfoJCheckBoxActionPerformed(evt);
            }
        });

        jLabel13.setText("开始日期：");

        jLabel15.setText("星期：");

        billInfoWeekJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日" }));
        billInfoWeekJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billInfoWeekJComboBoxActionPerformed(evt);
            }
        });

        jLabel16.setText("付款：");

        billInfoPayJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "未付款", "已付款" }));

        jLabel14.setText("姓名：");

        billInfoSubmitJButton.setText("查询");
        billInfoSubmitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billInfoSubmitJButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("结束日期：");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(todayBillInfoJCheckBox)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billInfoBeginDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billInfoEndDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billInfoWeekJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billInfoPayJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billInfoUserNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(billInfoSubmitJButton)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(todayBillInfoJCheckBox)
                    .addComponent(jLabel13)
                    .addComponent(billInfoBeginDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(billInfoEndDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(billInfoWeekJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(billInfoPayJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(billInfoUserNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billInfoSubmitJButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        billInfoJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "编号", "姓名", "日期/星期", "饭馆", "总数", "人均", "是否付款", "付款金额", "付款时间"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        billInfoJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                billInfoJTableMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(billInfoJTable);

        javax.swing.GroupLayout billInfoJInternalFrameLayout = new javax.swing.GroupLayout(billInfoJInternalFrame.getContentPane());
        billInfoJInternalFrame.getContentPane().setLayout(billInfoJInternalFrameLayout);
        billInfoJInternalFrameLayout.setHorizontalGroup(
            billInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
            .addGroup(billInfoJInternalFrameLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        billInfoJInternalFrameLayout.setVerticalGroup(
            billInfoJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billInfoJInternalFrameLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
        );

        billInfoJInternalFrame.setBounds(10, 10, 920, 390);
        mainJDesktopPane.add(billInfoJInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        payBillJInternalFrame.setClosable(true);
        payBillJInternalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        payBillJInternalFrame.setTitle("填写付款信息");

        jLabel18.setText("姓名：");

        payBillUserNameJTextField.setEnabled(false);

        jLabel19.setText("付款金额：");

        payBillSubmitJButton.setText("提交");
        payBillSubmitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBillSubmitJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout payBillJInternalFrameLayout = new javax.swing.GroupLayout(payBillJInternalFrame.getContentPane());
        payBillJInternalFrame.getContentPane().setLayout(payBillJInternalFrameLayout);
        payBillJInternalFrameLayout.setHorizontalGroup(
            payBillJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payBillJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payBillUserNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payBillMoneyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(payBillSubmitJButton)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        payBillJInternalFrameLayout.setVerticalGroup(
            payBillJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payBillJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(payBillJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(payBillUserNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(payBillMoneyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payBillSubmitJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        payBillJInternalFrame.setBounds(90, 60, 420, 80);
        mainJDesktopPane.add(payBillJInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        userInofJMenu.setText("饭友信息维护");

        addUserInfoJMenuItem.setText("添加饭友信息");
        addUserInfoJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserInfoJMenuItemActionPerformed(evt);
            }
        });
        userInofJMenu.add(addUserInfoJMenuItem);

        queryUserInfoJMenuItem.setText("查询饭友信息");
        userInofJMenu.add(queryUserInfoJMenuItem);

        mainMenuBar.add(userInofJMenu);

        LunchInfoJMenu.setText("午饭信息维护");

        addLunchInfoMenuItem.setText("添加午饭信息");
        addLunchInfoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLunchInfoMenuItemActionPerformed(evt);
            }
        });
        LunchInfoJMenu.add(addLunchInfoMenuItem);

        queryLunchJMenuItem.setText("查询午饭信息");
        queryLunchJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryLunchJMenuItemActionPerformed(evt);
            }
        });
        LunchInfoJMenu.add(queryLunchJMenuItem);

        mainMenuBar.add(LunchInfoJMenu);

        billInfoJMenu.setText("账单信息维护");

        billInfoJMenuItem.setText("查询账单信息");
        billInfoJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billInfoJMenuItemActionPerformed(evt);
            }
        });
        billInfoJMenu.add(billInfoJMenuItem);

        mainMenuBar.add(billInfoJMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUserInfoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserInfoJMenuItemActionPerformed
        // TODO add your handling code here:
        this.userEmailJTextField.setText("");
        this.userNameJTextField.setText("");
        this.userPhoneNumberJTextField.setText("");
        this.addUserInfoJInternalFrame.setVisible(true);
    }//GEN-LAST:event_addUserInfoJMenuItemActionPerformed

    private void submitUserInfoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitUserInfoJButtonActionPerformed
        // TODO add your handling code here:
        String userName = this.userNameJTextField.getText().trim();
        String phoneNumber = this.userPhoneNumberJTextField.getText().trim();
        String email = this.userEmailJTextField.getText().trim();

        if(StringUtil.isBlank(userName)){
            JOptionPane.showMessageDialog(null, "用户名不能为空！");
            return;
        }
        
        User user = new User();
        user.setEmail(email);
        user.setPhoneNumber(phoneNumber);
        user.setUserName(userName);
        user.setYn(1);
        

        if(userService.addUser(user)){
            JOptionPane.showMessageDialog(null, "添加成功");
        }else{
            JOptionPane.showMessageDialog(null, "添加失败");
        }
    }//GEN-LAST:event_submitUserInfoJButtonActionPerformed

    private void addLunchInfoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLunchInfoMenuItemActionPerformed
        // TODO add your handling code here:
        initAddLunchPanel();
        this.addLunchInfoJInternalFrame.setVisible(true);
    }//GEN-LAST:event_addLunchInfoMenuItemActionPerformed

    private void addLunchInfoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLunchInfoJButtonActionPerformed
        // TODO add your handling code here:
        int restaurantId = this.restaurantJComboBox.getSelectedIndex();
        if(restaurantId <= 0){
            JOptionPane.showMessageDialog(null, "请选择饭馆");
            this.restaurantJComboBox.requestFocus();
            return;
        }
        String restaurantName = this.restaurantJComboBox.getSelectedItem().toString();
        String lunchDateStr = this.lunchDateJTextField.getText().trim();
        Date lunchDate = null;
        if(StringUtil.isBlank(lunchDateStr)){
            JOptionPane.showMessageDialog(null, "请输入吃饭日期");
            this.lunchDateJTextField.requestFocus();
            return;
        }else{
            try {
                lunchDate = new SimpleDateFormat("yyyy/MM/dd").parse(lunchDateStr);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "吃饭日期格式错误，应该是：yyyy/MM/dd");
                this.lunchDateJTextField.requestFocus();
                return;
            }
        }
        String week = this.lunchWeekJTextField.getText().trim();
        if(StringUtil.isBlank(week)){
            JOptionPane.showMessageDialog(null, "请输入吃饭星期");
            this.lunchWeekJTextField.requestFocus();
            return;
        }
        String allMoney = this.allMoneyJTextField.getText().trim();
        if(StringUtil.isBlank(allMoney)){
            JOptionPane.showMessageDialog(null, "请输入饭钱总金额");
            this.allMoneyJTextField.requestFocus();
            return;
        }else{
            try{
                Double.parseDouble(allMoney);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "饭钱总金额是数字");
                this.allMoneyJTextField.setText("");
                this.allMoneyJTextField.requestFocus();
                return;
            }
        }
        String averageMoney = this.averageMoneyJTextField.getText().trim();
        if(!StringUtil.isBlank(averageMoney)){
            try{
                Double.parseDouble(averageMoney);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "人均饭钱是数字");
                this.averageMoneyJTextField.setText("");
                this.averageMoneyJTextField.requestFocus();
                return;
            }
        }
        String userNames = "";
        List<User> users = new ArrayList<User>();
        Component[] components = this.lunchUserJPanel.getComponents();
        if(components != null && components.length > 0){
            for(Component component : components){
                if(component instanceof JCheckBox){
                    JCheckBox box = (JCheckBox) component;
                    if(box.isSelected()){
                        int userId = Integer.parseInt(box.getActionCommand());
                        String userName = box.getText().trim();
                        userNames = userNames + "_" + userName;
                        User user = new User();
                        user.setId(userId);
                        user.setUserName(userName);
                        users.add(user);
                    }
                }
            }
        }
        if(users.isEmpty()){
            JOptionPane.showMessageDialog(null, "请选择吃饭的人");
            return;
        }

        if(StringUtil.isBlank(averageMoney)){
            averageMoney = Double.parseDouble(allMoney)/(users.size()+1) + "";
        }

        LunchInfo info = new LunchInfo();
        info.setAllMoney(Double.parseDouble(allMoney));
        info.setAverageMoney(Double.parseDouble(averageMoney));
        info.setLunchDate(lunchDate);
        info.setRestaurantId(restaurantId);
        info.setRestaurantName(restaurantName);
        info.setUserNames(userNames);
        info.setWeek(week);
        info.setYn(1);

        try{
            boolean result = this.lunchInfoService.addLunchInfo(info);
            if(result){
                result = this.billInfoService.addBillInfos(info, users);
                if(result){
                    JOptionPane.showMessageDialog(null, "添加成功");
                    todayBillInfoJCheckBox.setSelected(true);
                    this.billInfoJMenuItemActionPerformed(evt);
                    return;
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "添加失败");
    }//GEN-LAST:event_addLunchInfoJButtonActionPerformed

    private void queryLunchJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryLunchJMenuItemActionPerformed
        // TODO add your handling code here:
        initShowLunchInfoJInternalFrame();
    }//GEN-LAST:event_queryLunchJMenuItemActionPerformed

    private void queryLunchSubmitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryLunchSubmitJButtonActionPerformed
        // TODO add your handling code here:
        Map<String, Object> cond = new HashMap<String, Object>();
        int restaurantId = queryLunchResJComboBox.getSelectedIndex();
        if(restaurantId > 0){
            cond.put("restaurantId", restaurantId);
        }
        String beginDate = queryLunchBtJTextField.getText().trim();
        if(!StringUtil.isBlank(beginDate)){
            cond.put("beginDate", beginDate);
        }
        String endDate = queryLunchEtJTextField.getText().trim();
        if(!StringUtil.isBlank(endDate)){
            cond.put("endDate", endDate);
        }
        String week = queryLunchInfoWeekJComboBox.getSelectedItem().toString();
        if(!StringUtil.isBlank(week)){
            cond.put("week", week);
        }
        List<LunchInfo> infos = this.lunchInfoService.queryLunchInfoByCond(cond);
        lunchInfoJTable.removeAll();
        String[] colunmName = new String[]{"编号","日期","星期","饭馆","总数","人均","名单"};
        Object[][] dataVector = new Object[1][7];
        DefaultTableModel tableModel = new GmmTableModel();
        if(infos != null && infos.size() > 0){
            dataVector = new Object[infos.size()][7];
            DateFormat df = new SimpleDateFormat("yyyy/MM/dd");
            for(int index = 0; index < infos.size(); index++){
                LunchInfo info = infos.get(index);
                dataVector[index][0] = info.getId();
                dataVector[index][1] = df.format(info.getLunchDate());
                dataVector[index][2] = info.getWeek();
                dataVector[index][3] = info.getRestaurantName();
                dataVector[index][4] = info.getAllMoney();
                dataVector[index][5] = info.getAverageMoney();
                dataVector[index][6] = info.getUserNames();
            }
        }
        tableModel.setDataVector(dataVector, colunmName);
        lunchInfoJTable.setModel(tableModel);
        adjustLunchInfoTableColumnSize(lunchInfoJTable);
        lunchInfoJTable.setEnabled(false);
    }//GEN-LAST:event_queryLunchSubmitJButtonActionPerformed

    private void billInfoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billInfoJMenuItemActionPerformed
        // TODO add your handling code here:
        initBillInfoJInternalFrame();
    }//GEN-LAST:event_billInfoJMenuItemActionPerformed

    private void billInfoWeekJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billInfoWeekJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billInfoWeekJComboBoxActionPerformed

    private void billInfoSubmitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billInfoSubmitJButtonActionPerformed
        // TODO add your handling code here:
        Map<String, Object> cond = this.buildCondForBillInfoQuery();
        List<BillInfo> infos = this.billInfoService.queryBillInfoByCond(cond);
        String[] colunmName = new String[]{"编号","姓名","日期/星期","饭馆","总数","人均","是否付款","付款金额","付款时间"};
        Object[][] dataVector = new Object[1][9];
        DefaultTableModel tableModel = new GmmTableModel();
        if(infos != null && infos.size() > 0){
            dataVector = new Object[infos.size()][9];
            DateFormat df = new SimpleDateFormat("yyyy/MM/dd");
            DateFormat dfPayTime = new SimpleDateFormat("yyyy/MM/dd hh:MM:ss");
            BillInfo info = null;
            for(int index = 0; index < infos.size(); index++){
                info = infos.get(index);
                dataVector[index][0] = info.getId();
                dataVector[index][1] = info.getUser().getUserName();
                dataVector[index][2] = df.format(info.getLunchInfo().getLunchDate()) + "/" + info.getLunchInfo().getWeek();
                dataVector[index][3] = info.getLunchInfo().getRestaurantName();
                dataVector[index][4] = info.getLunchInfo().getAllMoney();
                dataVector[index][5] = info.getLunchInfo().getAverageMoney();
                dataVector[index][6] = info.getPay() == 0 ? "<html><font color=red>否</font></html>" : "<html><font color=blue>是</font></html>";
                dataVector[index][7] = info.getPayMoney() <= 0 ? "" : info.getPayMoney();
                dataVector[index][8] = info.getPayTime() == null ? "" : dfPayTime.format(info.getPayTime());
            }
        }
        tableModel.setDataVector(dataVector, colunmName);
        billInfoJTable.setModel(tableModel);
        adjustBillInfoJTableSize(billInfoJTable);
    }//GEN-LAST:event_billInfoSubmitJButtonActionPerformed

    private void todayBillInfoJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayBillInfoJCheckBoxActionPerformed
        // TODO add your handling code here:
        if(todayBillInfoJCheckBox.isSelected()){
            billInfoBeginDateJTextField.setText("");
            billInfoBeginDateJTextField.setEnabled(false);
            billInfoEndDateJTextField.setText("");
            billInfoEndDateJTextField.setEnabled(false);
            billInfoWeekJComboBox.setSelectedIndex(0);
            billInfoWeekJComboBox.setEnabled(false);
        }else{
            billInfoBeginDateJTextField.setText("");
            billInfoBeginDateJTextField.setEnabled(true);
            billInfoEndDateJTextField.setText("");
            billInfoEndDateJTextField.setEnabled(true);
            billInfoWeekJComboBox.setSelectedIndex(0);
            billInfoWeekJComboBox.setEnabled(true);
        }
    }//GEN-LAST:event_todayBillInfoJCheckBoxActionPerformed

    private void billInfoJTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billInfoJTableMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() == 2) {
            String id = (billInfoJTable.getModel().getValueAt(billInfoJTable.getSelectedRow(), 0)).toString();
            String money = (billInfoJTable.getModel().getValueAt(billInfoJTable.getSelectedRow(), 5)).toString();
            BillInfo info = new BillInfo();
            info.setId(Integer.parseInt(id));
            info.setPayMoney(Double.parseDouble(money));
            boolean result = this.billInfoService.billPay(info);
            if(result){
                JOptionPane.showMessageDialog(null, "付款成功","提示",JOptionPane.INFORMATION_MESSAGE);
                this.billInfoSubmitJButtonActionPerformed(null);
            }else{
                JOptionPane.showMessageDialog(null, "付款失败","错误",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_billInfoJTableMouseReleased

    private void payBillJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBillJMenuItemActionPerformed
        // TODO add your handling code here:
        if (billInfoJTable.getSelectedRow() != -1) {
            if (billInfoJTable.getSelectedRowCount() > 1) {
                JOptionPane.showMessageDialog(null, "一次只能操作一条记录！");
            } else {
                String id = (billInfoJTable.getModel().getValueAt(billInfoJTable.getSelectedRow(), 0)).toString();
                String name = (billInfoJTable.getModel().getValueAt(billInfoJTable.getSelectedRow(), 1)).toString();
                payBillUserNameJTextField.setText(name);
                this.payBillMoneyJTextField.setText("");
                
                this.payBillId = Integer.parseInt(id);
                payBillJInternalFrame.setVisible(true);
                payBillMoneyJTextField.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "请选择需要取消付款的记录！");
        }
    }//GEN-LAST:event_payBillJMenuItemActionPerformed

    private void unpayBillJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unpayBillJMenuItemActionPerformed
        // TODO add your handling code here:
        if (billInfoJTable.getSelectedRow() != -1) {
            if (billInfoJTable.getSelectedRowCount() > 1) {
                JOptionPane.showMessageDialog(null, "一次只能操作一条记录！");
            } else {
                String id = (billInfoJTable.getModel().getValueAt(billInfoJTable.getSelectedRow(), 0)).toString();
                boolean result = this.billInfoService.unPayBill(Integer.parseInt(id));
                if(result){
                    JOptionPane.showMessageDialog(null, "取消付款成功：" + id, "提示", JOptionPane.INFORMATION_MESSAGE);
                    this.billInfoSubmitJButtonActionPerformed(null);
                }else{
                    JOptionPane.showMessageDialog(null, "取消付款失败","错误",JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "请选择需要取消付款的记录！");
        }
    }//GEN-LAST:event_unpayBillJMenuItemActionPerformed

    private void payBillSubmitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBillSubmitJButtonActionPerformed
        // TODO add your handling code here:
        int id = this.payBillId;
        if(id <= 0){
            JOptionPane.showMessageDialog(null, "请选择需要付款的记录！");
            return;
        }
        String money = this.payBillMoneyJTextField.getText().trim();
        try{
            Double.parseDouble(money);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "付款金额是数字！");
            payBillMoneyJTextField.setText("");
            payBillMoneyJTextField.requestFocus();
            return;
        }
        BillInfo info = new BillInfo();
        info.setId(id);
        info.setPayMoney(Double.parseDouble(money));
        boolean result = this.billInfoService.billPay(info);
        if(result){
            JOptionPane.showMessageDialog(null, "付款成功","提示",JOptionPane.INFORMATION_MESSAGE);
            this.payBillJInternalFrame.setVisible(false);
            this.billInfoSubmitJButtonActionPerformed(null);
        }else{
            JOptionPane.showMessageDialog(null, "付款失败","错误",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_payBillSubmitJButtonActionPerformed

    private Map<String, Object> buildCondForBillInfoQuery(){
        Map<String, Object> cond = new HashMap<String, Object>();
        if(todayBillInfoJCheckBox.isSelected()){
            cond.put("today", true);
        }
        String beginDate = billInfoBeginDateJTextField.getText().trim();
        if(!StringUtil.isBlank(beginDate)){
            cond.put("beginDate", beginDate);
        }
        String endDate = billInfoEndDateJTextField.getText().trim();
        if(!StringUtil.isBlank(endDate)){
            cond.put("endDate", endDate);
        }
        if(billInfoWeekJComboBox.getSelectedIndex() > 0){
            cond.put("week", billInfoWeekJComboBox.getSelectedItem().toString());
        }
        if(billInfoPayJComboBox.getSelectedIndex() > 0){
            cond.put("pay", billInfoPayJComboBox.getSelectedIndex()-1);
        }
        String userName = billInfoUserNameJTextField.getText().trim();
        if(!StringUtil.isBlank(userName)){
            cond.put("userName", userName);
        }
        return cond;
    }
    private void initBillInfoJInternalFrame(){
        billInfoBeginDateJTextField.setText("");
        billInfoWeekJComboBox.setSelectedIndex(0);
        billInfoPayJComboBox.setSelectedIndex(0);
        billInfoUserNameJTextField.setText("");
        String[] colunmName = new String[]{"编号","姓名","日期/星期","饭馆","总数","人均","是否付款","付款金额","付款时间"};
        Object[][] dataVector = new Object[1][9];
        List<BillInfo> infos = null;
        DefaultTableModel tableModel = new GmmTableModel();
        try{
            Map<String, Object> cond = this.buildCondForBillInfoQuery();
            infos = this.billInfoService.queryBillInfoByCond(cond);
        }catch(Exception e){
            e.printStackTrace();
        }
        if(infos != null && infos.size() > 0){
            dataVector = new Object[infos.size()][9];
            DateFormat df = new SimpleDateFormat("yyyy/MM/dd");
            DateFormat dfPayTime = new SimpleDateFormat("yyyy/MM/dd hh:MM:ss");
            BillInfo info = null;
            for(int index = 0; index < infos.size(); index++){
                info = infos.get(index);
                dataVector[index][0] = info.getId();
                dataVector[index][1] = info.getUser().getUserName();
                dataVector[index][2] = df.format(info.getLunchInfo().getLunchDate()) + "/" + info.getLunchInfo().getWeek();
                dataVector[index][3] = info.getLunchInfo().getRestaurantName();
                dataVector[index][4] = info.getLunchInfo().getAllMoney();
                dataVector[index][5] = info.getLunchInfo().getAverageMoney();
                dataVector[index][6] = info.getPay() == 0 ? "<html><font color=red>否</font></html>" : "<html><font color=blue>是</font></html>";
                dataVector[index][7] = info.getPayMoney() <= 0 ? "" : info.getPayMoney();
                dataVector[index][8] = info.getPayTime() == null ? "" : dfPayTime.format(info.getPayTime());
            }
        }
        tableModel.setDataVector(dataVector, colunmName);
        billInfoJTable.setModel(tableModel);
        adjustBillInfoJTableSize(billInfoJTable);
        this.billInfoJInternalFrame.setVisible(true);
    }

    private void adjustBillInfoJTableSize(JTable table){
        TableColumn columnModel = null;
        columnModel = table.getColumnModel().getColumn(0);
        columnModel.setMaxWidth(60);
        columnModel = table.getColumnModel().getColumn(1);
        columnModel.setMaxWidth(100);
        columnModel = table.getColumnModel().getColumn(2);
        columnModel.setMaxWidth(150);
        columnModel.setMinWidth(150);
        columnModel = table.getColumnModel().getColumn(3);
        columnModel.setMaxWidth(80);
        columnModel = table.getColumnModel().getColumn(4);
        columnModel.setMaxWidth(80);
        columnModel = table.getColumnModel().getColumn(5);
        columnModel.setMaxWidth(80);
        columnModel = table.getColumnModel().getColumn(6);
        columnModel.setMaxWidth(80);
        columnModel = table.getColumnModel().getColumn(7);
        columnModel.setMaxWidth(80);

    }
    
    private void initShowLunchInfoJInternalFrame(){
        String[] restaurantNames = RestaurantUtil.getRestaurantNames();
        if(restaurantNames != null && restaurantNames.length > 0){
            queryLunchResJComboBox.setModel(new DefaultComboBoxModel(restaurantNames));
        }
        queryLunchBtJTextField.setText("");
        queryLunchEtJTextField.setText("");
        queryLunchInfoWeekJComboBox.setSelectedIndex(0);
        lunchInfoJTable.removeAll();
        String[] colunmName = new String[]{"编号","日期","星期","饭馆","总数","人均","名单"};
        List<LunchInfo> infos = this.lunchInfoService.queryAllLunchInfo();
        if(infos != null && infos.size() > 0){
            Object[][] dataVector = new Object[infos.size()][7]; 
            DateFormat df = new SimpleDateFormat("yyyy/MM/dd");
            for(int index = 0; index < infos.size(); index++){
                LunchInfo info = infos.get(index);
                dataVector[index][0] = info.getId();
                dataVector[index][1] = df.format(info.getLunchDate());
                dataVector[index][2] = info.getWeek();
                dataVector[index][3] = info.getRestaurantName();
                dataVector[index][4] = info.getAllMoney();
                dataVector[index][5] = info.getAverageMoney();
                dataVector[index][6] = info.getUserNames();
            }
            DefaultTableModel tableModel = new GmmTableModel();
            tableModel.setDataVector(dataVector, colunmName);
            lunchInfoJTable.setModel(tableModel);
            adjustLunchInfoTableColumnSize(lunchInfoJTable);
            lunchInfoJTable.setEnabled(false);
        }
        this.showLunchInfoJInternalFrame.setVisible(true);
    }

    private void adjustLunchInfoTableColumnSize(JTable table){
        TableColumn columnModel = null;
        columnModel = table.getColumnModel().getColumn(0);
        columnModel.setMaxWidth(80);
        columnModel = table.getColumnModel().getColumn(1);
        columnModel.setMaxWidth(180);
        columnModel = table.getColumnModel().getColumn(2);
        columnModel.setMaxWidth(120);
        columnModel = table.getColumnModel().getColumn(3);
        columnModel.setMaxWidth(100);
        columnModel = table.getColumnModel().getColumn(4);
        columnModel.setMaxWidth(100);
        columnModel = table.getColumnModel().getColumn(5);
        columnModel.setMaxWidth(100);
    }
    /**
    * @param args the comm and line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GiveMeMoneyJFrame frame = new GiveMeMoneyJFrame();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu LunchInfoJMenu;
    private javax.swing.JButton addLunchInfoJButton;
    private javax.swing.JInternalFrame addLunchInfoJInternalFrame;
    private javax.swing.JMenuItem addLunchInfoMenuItem;
    private javax.swing.JInternalFrame addUserInfoJInternalFrame;
    private javax.swing.JMenuItem addUserInfoJMenuItem;
    private javax.swing.JTextField allMoneyJTextField;
    private javax.swing.JTextField averageMoneyJTextField;
    private javax.swing.JTextField billInfoBeginDateJTextField;
    private javax.swing.JTextField billInfoEndDateJTextField;
    private javax.swing.JInternalFrame billInfoJInternalFrame;
    private javax.swing.JMenu billInfoJMenu;
    private javax.swing.JMenuItem billInfoJMenuItem;
    private javax.swing.JTable billInfoJTable;
    private javax.swing.JComboBox billInfoPayJComboBox;
    private javax.swing.JButton billInfoSubmitJButton;
    private javax.swing.JPopupMenu billInfoTableJPopupMenu;
    private javax.swing.JTextField billInfoUserNameJTextField;
    private javax.swing.JComboBox billInfoWeekJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lunchDateJTextField;
    private javax.swing.JTable lunchInfoJTable;
    private javax.swing.JPanel lunchUserJPanel;
    private javax.swing.JTextField lunchWeekJTextField;
    private javax.swing.JDesktopPane mainJDesktopPane;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JInternalFrame payBillJInternalFrame;
    private javax.swing.JMenuItem payBillJMenuItem;
    private javax.swing.JTextField payBillMoneyJTextField;
    private javax.swing.JButton payBillSubmitJButton;
    private javax.swing.JTextField payBillUserNameJTextField;
    private javax.swing.JTextField queryLunchBtJTextField;
    private javax.swing.JTextField queryLunchEtJTextField;
    private javax.swing.JComboBox queryLunchInfoWeekJComboBox;
    private javax.swing.JMenuItem queryLunchJMenuItem;
    private javax.swing.JComboBox queryLunchResJComboBox;
    private javax.swing.JButton queryLunchSubmitJButton;
    private javax.swing.JMenuItem queryUserInfoJMenuItem;
    private javax.swing.JComboBox restaurantJComboBox;
    private javax.swing.JInternalFrame showLunchInfoJInternalFrame;
    private javax.swing.JButton submitUserInfoJButton;
    private javax.swing.JCheckBox todayBillInfoJCheckBox;
    private javax.swing.JMenuItem unpayBillJMenuItem;
    private javax.swing.JTextField userEmailJTextField;
    private javax.swing.JMenu userInofJMenu;
    private javax.swing.JTextField userNameJTextField;
    private javax.swing.JTextField userPhoneNumberJTextField;
    // End of variables declaration//GEN-END:variables

}
